### PR TITLE
Improvements.

### PR DESCRIPTION
**Pull request by DxsSucuk**
* Added longer Timeouts.
* Added Pull Request and Issue Templates.
* Added support for Proxys.
* Added Code of conduct and Contributing.
* Added Java CI for automatic builds.
* Usage of the StandardCharsets instead of a string for UTF-8.
* Removed unused Mojang Auth url.
* Made Profile retrieval optional.
* Clean up a bit.

### CODE REVIEW

**Comment by DxsSucuk** [comment]
Should be ready now @Litarvan !

**Comment by Litarvan** [comment]
Well that's nice :)

It would be cool to overload the Authenticator methods with ones without the Proxy argument, to not break the compatibility and for the developer experience.
Also, the Mojang auth URL was indeed used! Not in the code, but by users of the library to give to the Authenticator constructor (c.f. the README), it must be brought back before merging

**Comment by DxsSucuk** [comment]
Understandable, I will add overload methods to hide the proxy argument.
But why is the Mojang Auth URL need? Those Auth Servers have been shutdown and do not work anymore, so keeping it is not really needed. Instead users should switch to the Microsoft Auth.

**Comment by DxsSucuk** [comment]
@Litarvan Should be ready now.

I added back the Mojang Auth URL but with a deprecated tag so developers know that it is not recommended to use.

**Comment by DxsSucuk** [comment]
@Litarvan ?

**Pull request merged**
